# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
# === Prompt format ===
format = """
 $status\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break $character"""

# === Color palettes ===
palette = 'tokyonight'

[palettes.tokyonight] # Tokyo Night Dark color scheme
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

yellow2 = '#ff9e64'
cyan2 = '#73daca'
cyan3 = '#b4f9f8'
blue2 = '#2ac3de'

[palettes.ayu] # Ayu dark color scheme
black = '#1e232b'
red = '#ea6c73'
green = '#7fd962'
yellow = '#f9af4f'
blue = '#53bdfa'
magenta = '#cda1fa'
cyan = '#90e1c6'
white = '#c7c7c7'

black2 = '#686868'
red2 = '#f07178'
green2 = '#aad94c'
yellow2 = '#ffb454'
blue2 = '#59c2ff'
magenta2 = '#d2a6ff'
cyan2 = '#95e6cb'
white2 = '#ffffff'

[palettes.catppuccin] # Catppuccin Mocha color pallete
black = '#45475a'
red = '#f38ba8'
green = '#a6e3a1'
yellow = '#f9e2af'
blue = '#89b4fa'
magenta = '#f5c2e7'
cyan = '#94e2d5'
white = '#a6adc8'

black2 = '#585b70'
red2 = '#f37799'
green2 = '#89d88b'
yellow2 = '#ebd391'
blue2 = '#74a8fc'
magenta2 = '#f2aede'
cyan2 = '#6bd7ca'
white2 = '#bac2de'
# === Module configuration ===

[status]
disabled = false
symbol = "\uf467"
not_executable_symbol = "\U0000f013"
not_found_symbol = "\uf002"
sigint_symbol = "\uf426"
signal_symbol = "\U0000223f"
map_symbol = true
style = 'bold fg:red'
format = "[\uf444 $symbol $status \uf444]($style)"

[username]
style_user = 'fg:yellow'
style_root = 'bold fg:yellow'
show_always = true
format = "[\uf444 \uf007 $user]($style)"

[hostname]
ssh_only = false
ssh_symbol = "\ueb01 "
trim_at = ''
style = 'fg:yellow'
format = "[@$hostname [$ssh_symbol](fg:cyan)\uf444]($style)"

[directory]
truncation_length = 8
truncate_to_repo = false
truncation_symbol = '.../'
style = 'fg:green'
repo_root_style = 'bold fg:cyan2'
repo_root_format = "[\uf444 \uf07b]($style) [$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) [\uf444]($style)"
read_only = " \uf456"
read_only_style = "bold fg:red"
format = "[\uf444 \uf07b $path[$read_only]($read_only_style) \uf444]($style)"

[git_branch]
symbol = "\ue725"
style = 'fg:magenta'
format = "[\uf444 $symbol $branch ]($style)"

[git_status]
style = 'fg:magenta'
format = "[($all_status$ahead_behind )\uf444]($style)"

[cmd_duration]
min_time = 0
show_milliseconds = true
style = 'fg:blue'
format = "[\uf444 \uf253 $duration \uf444]($style)"

[line_break]
disabled = false

[character]
success_symbol = "[\u2009\u2937 ](bold fg:green)"
error_symbol = "[\u2009\u2937 ](bold fg:red)"
format = "$symbol "
